package users

import (
	"errors"
	"events-app/db"
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
)

type User struct {
	ID        int64
	Login     string `binding:"required"`
	Email     string `binding:"required"`
	Password  string `binding:"required"`
	FirstName string
	LastName  string
}

func SignUp(ctx *gin.Context) {
	// Parsing users' JSON POST request
	var user User
	err := ctx.ShouldBindJSON(&user)
	if err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// create new user in the users DB
	err = user.New()
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, gin.H{"!message": "Could not create user!", "error": err.Error()})
		return
	}

	ctx.JSON(http.StatusCreated, gin.H{"message": "User successfully created!"})

}

// create new user method
func (u *User) New() error {
	query := "INSERT INTO users (login, email, password) VALUES ($1, $2, $3)"
	stmt, err := db.DB.Prepare(query)
	if err != nil {
		log.Fatalf("Error preparing the query: v%\n", err)
	}

	defer stmt.Close()

	result, err := stmt.Exec(u.Login, u.Email, u.Password)
	if err != nil {
		return errors.New(err.Error())
	}
	// converting user's plain text password into hashed one

	// assign user id generated by the DB
	u.ID, _ = result.LastInsertId()

	return nil
}
